name: winnepacacabot

volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:

services:
  app:
    container_name: winnepacacabot-app
    image: ranger-4297/yagpdb-winnepacaca
    build:
      context: ../
      dockerfile: yagpdb_docker/Dockerfile
    restart: unless-stopped
    command:
      # - "/app/yagpdb"
      - "-all"
      - "-pa"
      - "-exthttps=false"
      - "-https=false"
    depends_on:
      - redis
      - db
    networks:
      - default
    volumes:
      - cert_cache:/app/cert
      - soundboard:/app/soundboard
    ports:
      - '8089:80'
      - '9999:443'
    env_file:
      - app.env

  redis:
    container_name: winnepacacabot-redis-db
    image: docker.io/redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  db:
    container_name: winnepacacabot-postgres-db
    image: docker.io/postgres:11
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.env