name: veilbot

volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:

services:
  app:
    container_name: veilbot-app
    image: RhykerWells/yagpdb-iota
    build:
      context: ../
      dockerfile: yagpdb_docker/Dockerfile
    restart: unless-stopped
    command:
      # - "/app/yagpdb"
      - "-all"
      - "-pa"
      - "-exthttps=true"
      - "-https=false"
    depends_on:
      - redis
      - db
    networks:
      - default
    volumes:
      - cert_cache:/app/cert
      - soundboard:/app/soundboard
    ports:
      - '8086:80'
      - '9998:443'
    env_file:
      - app.iota.env

  redis:
    container_name: veilbot-redis-db
    image: docker.io/redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  db:
    container_name: veilbot-postgres-db
    image: docker.io/postgres:11
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.iota.env